### ISSUE TITLE
Contributing Guide: How to write a test generator

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#140]
https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#writing-a-new-test-suite-generator

**Comment by dvberkel** [comment]
Which languages have a test generator?

**Comment by dvberkel** [comment]
I found

* [ruby](https://github.com/exercism/xruby)

**Comment by kytrinyx** [comment]
Go also has generators.

```
$ find . -name example_gen.go
./exercises/bob/example_gen.go
./exercises/clock/example_gen.go
./exercises/connect/example_gen.go
./exercises/custom-set/example_gen.go
./exercises/gigasecond/example_gen.go
./exercises/hamming/example_gen.go
./exercises/largest-series-product/example_gen.go
./exercises/leap/example_gen.go
./exercises/meetup/example_gen.go
./exercises/raindrops/example_gen.go
./exercises/rna-transcription/example_gen.go
./exercises/roman-numerals/example_gen.go
./exercises/word-count/example_gen.go
```

**Comment by petertseng** [comment]
And Scala's generators are https://github.com/exercism/xscala/tree/master/testgen/src/main/scala

**Comment by petertseng** [comment]
What parts of writing a generator will be common between all the tracks?

**Comment by dvberkel** [comment]
That depends. The generators that I saw are all written in the track language. This makes sense, because track maintainers can easily change the generator.

But this isn't strictly necessary. I can imagine that there is a tool that reads in the canonical-data and a template specific to the language and maybe the exercise that will generate the test file.

But I am not sure what the intended path is.

**Comment by catb0t** [comment]
Factor's *singular* generator intended to write tests for *all* the exercises is written in Factor here: https://github.com/catb0t/exercism.factor/tree/master/exercism

Though, it's not done until I've figured out how to locally unmalform the exercise data, because right now you almost need a different program for each exercise which is, as I've remarked before, annoying, yet inconvenient to fix.

**Comment by kytrinyx** [comment]
@catb0t as you work on unmalforming the exercise data, would you see if you come up with a suggestion for a more normalized format? I think it would be great to discuss specific suggestions.

**Comment by petertseng** [comment]
Closed for https://github.com/exercism/docs/issues/23 I suppose.
