### ISSUE TITLE
README for Custom-Set is too ambiguous

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/x-common#169]
I just reviewed a submission on the EcmaScript track in which the submitter chose to implement his Custom Set by extending Set!

I don't think this is the intention of the exercise, but the README doesn't explicitly forbid the use of the Set class like, for example, the Strain README says 'keep your hands off filter/reduce...'

I know this would be an appropriate caveat in Java, JS, and ES-- what about the other tracks?

**Comment by NobbZ** [comment]
For xerlang we don't have implemented that exercise so far, but in theory the erlang stdlib provides two kinds of sets, a third kind of set is available via a library which is not part of stdlib but installed by default on most systems. So yes, in theory one could implement this exercise in erlang just by wrapping calls.

Also there is elixir, which already has this exercise. There you can use the erlang sets easily, also the elixir stdlib does provide some set implementations. So again one could easily just wrap calls. Since this exercise uses the ``Set``-behaviour (just consider it like a Java-Interface) defined in stdlib it is very easy to wrap to another implementation. You know in advance, that the name of the function is the same as yours.

Anyway. There are many problems which can be mapped to something in the stdlib very easily. Some of the exercises encourage the use of the stdlib in such cases (eg gigasecond), most discourage them. Its not easy to find an instinctive way inbetween.

So in general I do ask the following questions by myself:
1. Does this map directly to something already in stdlib?
2. Is this something every programmer should have done by hand, just to understand the underlying datastructure/algorithms?
3. Would this be unnecessarily complex when defining it by hand and not using stdlib?

When I have answered these questions, then I decide how to process based on the answers.

But even then, you can't answer this stuff directly. I don't even consider direct mapping to stdlib rule breaking. I just consider it rule bending. In my university, we are often told, a good programmer is who knows his/her stdlib and uses it accordingly. BUT another thing we here very often is that a good programmer is who is able to reimplement some basic parts of his/her stdlib.

So in many cases, I recognize the first submission which directly maps as a proof of knowing the stdlib and put that submission on hold for a week or two until I take another look at it. When it has evolved everything is fine and I nit on the newer iterations, seeing them as proof one can reimplement. When there has been no new iteration I do a single comment, pointing at "first principles".

And mentioning "first principles" right now, we have them, so why mention them in about 90% of the readmes all over again?

**Comment by matthewmorgan** [comment]
@NobbZ sounds like you are advocating for leaving the README alone and coaching people to try it both ways: stdlib and by hand.  

That seems like a reasonable approach to me.  In this particular exercise I think each way of solving has value.

**Comment by NobbZ** [comment]
That's a very good summary of my post, yes.

But if we see it this way, we need to make sure it's seen like this
everywhere. Eg the rubytrack does enforce first principle by overwriting
parts of the stdlib in some exercises, dunno if there are other tracks
doing this or if it would even be possible on other tracks.

Matthew Morgan <notifications@github.com> schrieb am Fr., 22. Jan. 2016
13:29:

**Comment by kytrinyx** [comment]
In Ruby it's particularly important to make sure people understand the datastructures, because the Ruby track has a lot more code newbies in it. If you already know what a set is and all you want to do is learn how to write erlang, then it's useful to just use the stdlib.

**Comment by matthewmorgan** [comment]
@kytrinyx --interesting: how do you know that Ruby has more newbies?

**Comment by kytrinyx** [comment]
Ruby, Python, JavaScript and Java are the tracks that tend to have newbies. I know this from looking at code :)

This is compared to C++, Rust, Go, Haskell, Lisp, etc.

**Comment by matthewmorgan** [comment]
Well, I'm sure a small number of us are bringing down the curve on JS and
Java!  ;)

On Fri, Jan 22, 2016 at 4:39 PM, Katrina Owen <notifications@github.com>
wrote:

> Ruby, Python, JavaScript and Java are the tracks that tend to have
> newbies. I know this from looking at code :)
>
> This is compared to C++, Rust, Go, Haskell, Lisp, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/x-common/issues/169#issuecomment-174058743>.
>



-- 
Matt Morgan
Director of Technology
Dulcet Software LLC
(734) 926-8142

**Comment by kytrinyx** [comment]
Oh, for sure--those tracks also have artisans and polyglots. I think Ruby is the one where there are overwhelmingly large number of newbies so as to make it noticeable.
