### ISSUE TITLE
Is there a way to add sanity checks for a track?

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/x-common#174]
For the Lua track I have a script that I keep locally that makes sure that every example passes all tests for that problem. Long term I may update it to check for obvious style or formatting problems. I'd really like for this to not be stored locally so that it can be used by other contributors.

So...
- is there a common way to plug this in to Travis to ensure that pull requests don't break anything?
- is there some other common method that track maintainers are using that covers this?

**Comment by petertseng** [comment]
I believe many tracks do this.

* xgo's is almost too easy because it doesn't matter what the filenames are: https://github.com/exercism/xgo/blob/master/.travis.yml#L48
* xelixir uses an environment variable to say to test the examples: https://github.com/exercism/xelixir/blob/master/.travis.yml#L12 and https://github.com/exercism/xelixir/blob/master/hello-world/hello_world_test.exs
* xruby copies the `example.rb` file to be the expected name, runs a small script to un-skip tests which are skipped by default, then runs them: https://github.com/exercism/xruby/blob/master/.travis.yml#L11 https://github.com/exercism/xruby/blob/master/Makefile#L19 https://github.com/exercism/xruby/blob/master/lib/disable_skip.rb

I guess what I'm saying is, the tracks that I've looked at mostly have this and they all just do it their custom way (since how to execute a test file varies from language to language).

So in Lua's case I imagine a possible solution would be to put your script into the repo and have Travis run it by editing `.travis.yml` appropriately.

**Comment by ryanplusplus** [comment]
Thanks @petertseng, I will go that route

**Comment by LegalizeAdulthood** [comment]
For C++, I have the `.travis.yml` file run the build and the build compiles the code and runs the tests.  Failing tests make for a failing travis build, which I think is the best way to report this.  Pull requests report the status of the travis build before merging, so a track maintainer knows whether things are still good or not.
