### ISSUE TITLE
crypto-square implementations disagree with README in many tracks

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/x-common#190]
Taken from [xjava](https://github.com/exercism/xjava/issues/55#issuecomment-193389759):

Chunk sizes are wrong: The README gives several examples of how to deal with strings of text that can be made into perfect ( ie n X n ) squares, and those that can be made into imperfect ( r X c ) squares. In all the README examples, the imperfect squares are r X c with the additional constraint that r >= c.

As documented by @jtigger [here](https://github.com/exercism/exercism.io/issues/2432#issuecomment-118467422) most of the tracks take a 26-letter string and chunk it in to 5, 5, 4, 4, 4, 4. This is not the behavior specified in the README, and seems like a error from early on that got propagated to many tracks.

There's no json file for this in x-common, but it appears this needs to be changed in many places, not just on the Java track.

If I'm missing something please let me know, but it seems like this is a good case for common test data.

**Comment by kytrinyx** [comment]
I remember having trouble with inconsistencies on this before, but I've never taken the time to go through everything and tidy it up.

I'd love to have a canonical list of test cases (`crypto-square.json` would be great).

**Comment by kytrinyx** [comment]
Pinging @exercism/track-maintainers in case you're not watching the repo :)

**Comment by ErikSchierboom** [comment]
Just to be clear, in the linked post it shows show variants of how tracks implement the algorithm for the strings "Madness, and then illumination." and "Vampires are people too!". What is the correct output for those strings?

**Comment by petertseng** [comment]
So the question is whether the imperfect squares (which have r rows and c columns) should have `r >= c` or `c >= r`?

Well, I don't care how we decide as long as we all reach some consensus, but if I look at the [.yml file for the exercise](https://github.com/exercism/x-common/blob/master/crypto-square.yml#L4), it lists source of http://users.csc.calpoly.edu/~jdalbey/103/Projects/ProgrammingPractice.html, and the example on that page is a `c >= r` example, as it says:

> so it is written into a rectangle with 7 rows and 8 columns. 

This is supported by the following sentence in the README:

> A message between 5 and 8 characters long should use a rectangle 3 characters wide.

So the message "abcde" fills in this way (`c >= r`):

    abc
    de

Rather than this way (`r >= c`):

    ab
    cd
    e

The following portion also supports `c >= r`

> Which has length: 30
> And splits into 5 6-character rows: 

---

Finally, I found a contradictory sentence in the README:

> Broken into 8-character columns, it yields 7 rows.

This sentence is contradictory because if a column has 8 characters, that implies there will be 8 rows, by definition. The sentence should read something similar to "Broken into 8 columns, it yields the 7 rows" (this is a `c >= r` definition)

This would bring it in line with the example right below that sentence (the example from the page linked above, in fact!):

    ifmanwas
    meanttos
    tayonthe
    groundgo
    dwouldha
    vegivenu
    sroots

---

If we believe that it should be `c >= r`, the output for "Madness, and then illumination." is "msemo aanin dnin ndla etlt shui" and the output for "Vampires are people too!" is "vrel aepe mset paoo irpo"

I don't have available code that implements `r >= c` right now, sorry

**Comment by kytrinyx** [comment]
@petertseng This is a fantastic summary of the problem, thank you so much for doing the analysis and exposé.

The origin of this exercise is the "square code" exercise from here: http://users.csc.calpoly.edu/~jdalbey/103/Projects/ProgrammingPractice.html

**Comment by matthewmorgan** [comment]
@petertseng thanks so much.  @jtigger and I have been working on a PR for x-common to clarify the parameters for this exercise.  Can we continue the discussion there?

**Comment by ErikSchierboom** [comment]
Wow, thanks a lot for the clarification @petertseng !

**Comment by verdammelt** [comment]
Total tangent here - sorry - but while we are talking about cryptosquares I wanted to share this phrase in Latin which reads the same even when encoded as a cryptosquare:

 > sator arepo tenet opera rotas

(It was found in Pompeii (amongst a few other places)).

**Comment by IanWhitney** [comment]
I believe this can be closed. the `r` vs `c` question has been covered, and there is now a canonical test file.
