### ISSUE TITLE
Improve Sum of Multiples exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#198]
See the discussions in https://github.com/exercism/exercism.io/issues/2654 and https://github.com/exercism/xgo/issues/256

There's been a bit of confusion due to the whole "defaults" thing (use 3 and 5 as defaults if no arguments are passed). I made that up sometime at the dawn of Exercism, and I regret it.

I would much rather have a cleaner problem statement with no defaults.

In order to fix this we would need to

- [x] clarify the README
- [x] create a canonical set of shared test inputs/outputs in sum-of-multiples.json
- [x] fix all of the existing implementations

**Comment by alebaffa** [comment]
Hi, is this exercise still under revision?

**Comment by kytrinyx** [comment]
Yeah, if you look at all the related links in this thread, the issue needs to stay open as long as there are green badges:

<img width="687" alt="screen shot 2016-08-07 at 9 11 02 am" src="https://cloud.githubusercontent.com/assets/276834/17463230/e56f95ca-5c7e-11e6-84ec-ffc782f97246.png">

**Comment by NobbZ** [comment]
I will try to tackle xlfe this weekend.

**Comment by NobbZ** [comment]
I took the freedom to tackle `xlfe` as well as `xclojure`.

But I am far from beeing an expert about the various lisp dialects and there different idioms, so building up the new testsuites was a very straightforward mechanical process, for sclojure, I even used 2 replace by regexp of my editor (against the lfe version) and I was ready to go in theory, but I fine tuned a little bit, because in the original suite there was used a `zero?` predicate instead of checking equality to `0`…

So both should be reviewed by track maintainers or track-VIPs at least.

**Comment by NobbZ** [comment]
Both got merged so it should be done now.

**Comment by petertseng** [comment]
Great job, all involved
