### ISSUE TITLE
palindrome-products: README is confusing

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#208]
The palindrome products README is short and potentially confusing.

> The description of palindrome product could use a few more examples. It should also clarify that there may be more than 1 solution to the product like with 9 => [[1, 9], [3, 3]], and that all single digits were considered palindrome products. Perhaps a link to the wiki page would be good? - @mayppong
> 
> I just did this exercise and it took me awhile to figure this out as well. I came here to post an issue to discuss with anyone and this was already here. +1 to making this more clear somehow. - @dalexj

See the full discussion in https://github.com/exercism/xelixir/issues/68

**Comment by remcopeereboom** [comment]
I took a stab at a better readme. There are some questions still unanswered:
 - Do we want to find all the palindromic products (expensive) or only it's smallest and largest?
 - Are the factors (91, 99) and (91, 99) considered distinct or not?

# README
A palindromic number reads the same both ways.  A palindrome product is a product of two numbers that is a palindromic number. For example, 121 is a palindrome product because it is a palindrome and it is the product of two numbers (11 * 11). It's possible (and common) for a palindrome product to be the product of multiple combinations of numbers. For example, the palindrome product 9 has the factors (1, 9), (3, 3), and (9, 1).

Write a program that given a range of numbers, returns the smallest and largest palindromic product within that range, along with it's products.

### Example
Given the range [10, 99]...

The largest palindrome is 9009. It's factors are (91, 99) and (99, 91).
The smallest palindrome is 121. It's factors are (11, 11).

**Comment by kotp** [comment]
I think if (3, 3) and (3, 3) are not considered distinct, then (9, 1) and (1, 9) should not be considered distinct either.  From what I have seen, there is a listing that looks something like this:  (1, 9), (3, 3), (1, 9), which indicates that it is missing the other (3, 3).

You know the old adage, If change is due of 15 cents, and you must pay the change in two coins, but one coin must not be a dine... It must be a nickel and a dime, because the other coin is a dime.  Still two different coins, and can be ordered in either way, though two nickels would (arguably) be indistinguishable in either place, there are still two arrangements.

**Comment by remcopeereboom** [comment]
I don't agree with your argument, _precisely because (3, 3) and (3, 3) are indistinguishable which to me makes them one arrangement_. Still, if this is a necessary condition of the solution than we can included. If not, than perhaps the simplest solution then is to not care about duplicates and have the checks be ambivalent about duplicates?

**Comment by kytrinyx** [comment]
I think that this problem it makes sense for the results to be order-independent. In other words: (1, 9) is equivalent to (9, 1) (but it's not a set in the comp sci sense of the word, because (3, 3) is a legit answer, but (3) is not. Sets don't have duplicates.

**Comment by robkeim** [comment]
@remcopeereboom - I'm digging around in old issues and am wondering if you were planning on sending a PR for this?

Here are responses to your questions based on the anecdotal evidence of what's already been implemented:

> Do we want to find all the palindromic products (expensive) or only it's smallest and largest?

All of the tracks that have implemented this exercise so far have done only smallest and largest

>Are the factors (91, 99) and (91, 99) considered distinct or not?

In terms of the pairs of factors (x, y) and (y, x) most of the tracks seem to check for the presence of (x, y) where x <= y.

Here are the tracks that have implemented the exercise today for reference:
- [C#](https://github.com/exercism/xcsharp/blob/master/exercises/palindrome-products/PalindromeTest.cs)
- [CoffeeScript](https://github.com/exercism/xcoffeescript/blob/master/exercises/palindrome-products/palindrome_products_test.spec.coffee)
- [Ecmascript](https://github.com/exercism/xecmascript/blob/master/exercises/palindrome-products/palindrome-products.spec.js)
- [Elixir](https://github.com/exercism/xelixir/blob/master/exercises/palindrome-products/palindrome_products_test.exs)
- [F#](https://github.com/exercism/xfsharp/blob/master/exercises/palindrome-products/PalindromeTest.fs)
- [Go](https://github.com/exercism/xgo/blob/master/exercises/palindrome-products/palindrome_products_test.go)
- [Haskell](https://github.com/exercism/xhaskell/blob/master/exercises/palindrome-products/test/Tests.hs)
- [Java](https://github.com/exercism/xjava/blob/master/exercises/palindrome-products/src/test/java/PalindromesTest.java)
- [Javascript](https://github.com/exercism/xjavascript/blob/master/exercises/palindrome-products/palindrome-products.spec.js)
- [Perl5](https://github.com/exercism/xperl5/blob/master/exercises/palindrome-products/palindrome.t)
- [Python](https://github.com/exercism/xpython/blob/master/exercises/palindrome-products/palindrome_products_test.py)
- [Ruby](https://github.com/exercism/xruby/blob/master/exercises/palindrome-products/palindrome_products_test.rb)
- [Scala](https://github.com/exercism/xscala/blob/master/exercises/palindrome-products/src/test/scala/PalindromeProductsTest.scala)
- [Swift](https://github.com/exercism/xswift/blob/master/exercises/palindrome-products/Tests/PalindromeProductsTests/PalindromeProductsTests.swift)

**Comment by remcopeereboom** [comment]
@robkeim 

> I'm digging around in old issues and am wondering if you were planning on sending a PR for this?

I wasn't planning on it, but I can :). I'll get to it tomorrow at the latest.

**Comment by remcopeereboom** [comment]
Just submitted a [pull request](https://github.com/exercism/x-common/pull/531).

**Comment by robkeim** [comment]
Thanks @remcopeereboom. I could have created the PR myself, but I didn't want to "steal" the credit for the work you'd already done :)

**Comment by remcopeereboom** [comment]
@robkeim Not that much work, but cheers anyway.

**Comment by robkeim** [comment]
Completed via #531
