### ISSUE TITLE
Should we use a pre-comma for the config.json?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#216]
See https://github.com/exercism/xswift/pull/130

The benefit is that there will be less noise when rearranging exercises. I suspect that it also decreases (only slightly, though) the risk of merge conflicts when adding new exercises.

**Comment by petertseng** [comment]
Do not feel strongly either way. Note that trailing comma only causes noise when adding an exercise to the end of the list. Pre-comma would cause noise when adding an exercise to the beginning of the list; this only works for us simply because we know that the first exercise for a track should be hello world and it will never change (admitted, not all tracks have implemented their hello world exercise).

Note that, for whatever reason, [commonly-accepted Haskell style](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#list-declarations) also uses pre-commas. So there is precedent in other languages.

I admit I am not used to it because I more often use languages where trailing comma are allowed, but it is a sensible choices for languages where trailing comma is not allowed.

**Comment by kytrinyx** [comment]
Right, we're very rarely going to add something to the beginning of the list. That said, it will happen.

I don't feel strongly about it either, and I'd like to wait for more voices to weigh in on it before we decide one way or another.

**Comment by kytrinyx** [comment]
I've thought about this some more, and I've come to the conclusion that it's not worth mandating one or the other. When someone starts implementing a track, or if they see that they're getting a lot of noise, then it's fine if they make this change, otherwise let's just leave it be.
