### ISSUE TITLE
[hamming] Do we need to restrict this exercise to DNA?

### ISSUE THREAD

**Issue by NobbZ** [exercism/x-common#323]
According to wikipedia (https://en.wikipedia.org/wiki/Hamming_distance) the hamming distance is a metric over strings in CS. To actually find a relationship to biology I had to dig a little bit deeper and it seemed to be just another application of Richard Hammings original idea from around 1950.

So I think that the algorithm itself can be applied to any sequence of things that can be either equal or not.

This conclusion also does lead to the following:

Currently we are refering to DNA in the README, but do not enforce it in the common testsuite. So I do think, if we want to stick to DNA, we should also introduce testcases for invalid strands. If we don't want to have those testcases, we should also change the README to allow arbitrary strings, we could use even "proper" story-telling then.

**Comment by petertseng** [comment]
DNA was probably relevant when hamming was called point-mutation. I imagine that by choosing to rename it to generic hamming we accept the possibility for non-DNA... though I can't find documentation of the decision (can someone help? I only found #184)

**Comment by kytrinyx** [comment]
@petertseng I can't recall why the change was made, but I think it might have been related to an issue we had with exercises with hyphens in the names (I can't remember why this was a problem, and we've obviously fixed it since).

I think that the exercise gets much more interesting if we don't restrict it to DNA. A friend of mine was telling me about the exploration she did in Swift when she made different assumptions (DNA, but millions of base pairs long vs any kind of strings so you could have encoding issues e.g. rune vs char). It was a much more powerful learning experience.

**Comment by Cohen-Carlisle** [comment]
Necroing! I must say that it didn't initially strike me as odd that `hamming` talked about DNA when I did the exercise, but now that this has been pointed out it does seem a little odd, distracting even, to have all this DNA stuff in a hamming exercise. On the other hand, it does give a nice real world application. It would be interesting to expand the amount of real world examples instead of limiting it to DNA.

**Comment by kytrinyx** [comment]
> It would be interesting to expand the amount of real world examples instead of limiting it to DNA.

Agreed, that would potentially make this a much more interesting exercise. The trade-off is that we'd probably have to push it farther back in a lot of language tracks, because encoding is sometimes very challenging. Probably worth it, though :)

**Comment by petertseng** [comment]
This issue was phrased as a question, and we answered the question (**No**, the exercise does not need to be restricted to DNA).

So it has served its purpose.

Now we want to know what to do as a result of this answer.

* Nothing at all
* Change README to not imply that DNA is the only application, but leave tests as they are
* Add tests that check that an error results from computing distance on non-DNA
* Change README to not imply that DNA is the only application, then add tests that check that a valid distance results from computing distance on non-DNA

So, if anyone wants to take any of the actions, open an issue or reuse this one.

Another exercise that checks error on non-DNA in https://github.com/exercism/x-common/blob/master/exercises/nucleotide-count/canonical-data.json#L46

I acknowledge that the option of "check that a valid distance results from computing distance on non-DNA" would not increase the difficulty but would increase the perceived difficulty.
