### ISSUE TITLE
xjulia builds are running long/hanging (?)

### ISSUE THREAD

**Issue by jtigger** [exercism/x-common#539]
In the last couple of days, I've noticed that builds on a couple of tracks I co-maintain have been hanging...  looking further, I found that there were a number of `xjulia` builds that are running for a considerable time (~45-50 mins)...

I also notice that there are multiple builds at once.  Right now there are four concurrent builds running in Travis for Exercism and all four are `xjulia`.  This apparently hits some limit and other builds are delayed until these either complete, are stopped, or timeout.

![image](https://cloud.githubusercontent.com/assets/470176/22745022/028cd3de-edd4-11e6-9b95-4408cf589c77.png)

I couldn't view the logs for the builds.   Any ideas of what might be happening?

@exercism/julia — thoughts?

**Comment by SaschaMann** [comment]
The macOS builds take a really long time to start up at the moment (up to an hour). As soon as they start, they finish within about a minute.

I thought it's still a result of the recent macOS issues that travis had. I know that it happens for other julia packages too that use Travis. I'm not really sure what causes it.

I could temporarily disable the macOS testing for now; I didn't know this causes issues for other tracks.

Are there any other tracks that experience the same issues with long macOS-startup times?

**Comment by petertseng** [comment]
Trying to figure out what could be happening here - if OSX plays a role, would one expect that the other tracks with OSX builds could also cause builds to back up?

* https://github.com/exercism/xcsharp/blob/master/.travis.yml
* https://github.com/exercism/xfsharp/blob/master/.travis.yml
* https://github.com/exercism/gui/blob/master/.travis.yml

In general, I had observed in the past that Travis only runs five jobs at a time, but I thought that was a per-repo limit. Hadn't seen the per-organisation limit (assuming that's what it is).

Can we try to test out a few situations, perhaps by creating some dummy repos in the org, some with OSX builds?

**Comment by petertseng** [comment]
As another sample point so that we can see the influence of other factors as well: If we are looking at tracks with many jobs per build, then we might look at https://github.com/exercism/xgo/blob/master/.travis.yml#L17-L20 which hilariously attempts to stay as close to **ten** jobs as possible without going over.

Another facet of my position where I was not clear in expression:

Oh no. I wish that to reason about my track's Travis builds I only need consider what my track is doing, and be blissfully unaware of any other tracks. That's the ideal world, of course. I get it, we are together one organisation and we're all in this together. Now, I personally didn't have any reason to believe in the past that my track's CI was being affected by others'. Why now is it being thrust into my awareness? Maybe I was just too inattentive in the past... recent events in my offline life have really highlighted to me my occasional inattentiveness, to my great chagrin.

**Comment by SaschaMann** [comment]
It may also be an issue with the julia integration in travis itself because the macOS start-up issue occurs in other julia repos unrelated to exercism, too:

![image](https://cloud.githubusercontent.com/assets/20866761/22750410/0364d54c-ee31-11e6-8292-04b410ee626e.png)

The dummy-repo testing that @petertseng suggested sounds like a good way to narrow it down.

---

@petertseng I simply didn't know that the Travis limits apply to organisations and not just single repos, sorry. The time when I started maintaing the repo was about when Travis had lots of issues with their macOS infrastructure [[1]](https://www.traviscistatus.com/incidents/9m337lnlxrqq) [[2]](https://www.traviscistatus.com/incidents/k79mjcv403c4) so I thought it was still a consequence of that. Otherwise I wouldn't have ignored it and investigated what causes this earlier.

**Comment by petertseng** [comment]
> @petertseng I simply didn't know that the Travis limits apply to organisations and not just single repos, sorry.

Ugh, I didn't either. This is bad news for the Go track, since now the Go track is also absolutely to blame for backing up other tracks' builds as well, with its TEN jobs. Rust track maybe too, with its seven.

I am sorry for that.

**Comment by petertseng** [comment]
I ran experiments and I know it's a really small sample size and I should experiment more to confirm, but with my limited tests I saw that an x-common build waits for an xgo build to complete before acting, whereas if there was no xgo build the x-common build started up quickly.

It would be great if the delay in the first x-common build (#540) was just a coincidence - more experimentation?

**Comment by ErikSchierboom** [comment]
I can confirm that both the C# and F# tracks have had this exact same problem. Our Unix builds run relatively fast, but the Mac builds have been on hold for tens of minutes on several occasions. 

@petertseng I've never really experience delays due to other tracks being run, but it might be simply because I got lucky.

**Comment by petertseng** [comment]
Since xjulia isn't using OSX builds anymore, and further the track maintainers have a reminder to re-enable the OSX builds when the startup time is good, don't need this open in x-common anymore.

As y'all can see above, I also took the opportunity to reduce xgo's Travis footprint. My apologies--I was the person who argued to increase it assuming that the five-job limit was per-repo not per-organisation.

**Comment by petertseng** [comment]
> I was the person who argued to increase it

Proof of my guilt: https://github.com/exercism/xgo/pull/316

**Comment by behrtam** [comment]
Maybe if new commits come too fast for slow builds `Auto cancellation` could also be of help: https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation
