### ISSUE TITLE
robot-name: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#580]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Robot Name exercise can be found in the [./exercises/robot-name/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/robot-name for the up-to-date list of
language tracks that have an implementation of the Robot Name exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/robot-name

**Comment by masters3d** [comment]
Hi @kytrinyx 

I'de like to propose to deprecate and reintroduce the exercise with a new name and requirement.
The new name I'd like to proposed is`RobotRegistry` which has prior art in the PHP track solution.
I've suggested this rename before: https://github.com/exercism/discussions/issues/12

I've tried to fixed the ambiguities but its turned out to be very hard to do and taxing: https://github.com/exercism/x-common/issues/731#issuecomment-296804339

I think this best way to move forward.

**Comment by kytrinyx** [comment]
I think the right way to move forward is to continue the discussion in #731 to figure out the right solution (deprecate this exercise and either create new exercises or rename this one). Either way #731 is where the decision seems to need to be made.

I'm going to close this, since we can't solve it until we know more.
