### ISSUE TITLE
F# List-Ops foldr tests/implementation 

### ISSUE THREAD

**Issue by hobbitjoe** [exercism/x-common#606]
The id and append test cases:
```
//id
foldr (fun item acc -> item :: acc) [] [1 .. big]
//append
foldr (fun item acc -> item :: acc) [100 .. big] [1 .. 99]
```
The arguments for the accumulator and the list to fold over are backwards compared to foldr in languages like haskell or even F#'s own foldBack function.

Below are two implentations that have been submitted for foldr
```
let foldr fn lst acc = foldl (flip fn) acc (reverse lst)
let foldr f acc xs = foldl (flip f) acc (reverse xs)
```

The top one I wrote has the function arguments in the order that would be expected of foldr, while the second one has the arguments in the order required to pass the test cases.  Were the test cases intended to be written this way or should the parameters passed to the foldr function be flipped in order to follow existing behaviors?

**Comment by petertseng** [comment]
First I have to ask, should this go in the https://github.com/exercism/xfsharp/issues instead, so it is known to those who actually know F#? Otherwise, people in x-common may give opinions not grounded in F# knowledge, and this may result in recommendations inapplicable to F#.

It seems to me that

* `foldr fn lst acc` is consistent with the https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/list.foldback%5b't,'state%5d-function-%5bfsharp%5d I see (take the list then the accumulator, in order to match with the fact that the accumulating function takes in an element and then the accumulator)
* `foldr f acc xs` is consistent with the `http://hackage.haskell.org/package/base-4.9.1.0/docs/Prelude.html#v:foldr` because Haskell would tend to put the list last. The list is the argument most likely to change and thus it is more likely that a function can be expressed in terms of fewer points.

It seems:

* Haskell and F# differ in this regard
* F#'s tests currently use the Haskell convention, given what you say

Shouldn't it be best to use the F# convention in the F# tests?

At this point, I reread my post and realize I have merely repeated your question. Alas, I have no basis on which to make any decision...

**Comment by hobbitjoe** [comment]
Ahhh thanks for the feedback, I'll close this issue and create one in the correct place.
