### ISSUE TITLE
wordy: Match bonus in description with canonical data

### ISSUE THREAD

**Issue by mienaikage** [exercism/x-common#738]
The bonus mentioned for the description in wordy (i.e. 5th power) is not in the canonical data. There is `cubed` in the canonical data which is vaguely similar, however the case having an expected `false` means an error or failure is to be raised according to the canonical data description.

Any preference for which it should be?

**Comment by petertseng** [comment]
The current state of affairs doesn't seem *incorrect*, but it may cause two unrelated things to seem related.

The https://github.com/exercism/x-common/blob/master/exercises/wordy/description.md would say that a track might add a test such as "What is B raised to the Eth power?" and expect an answer. Even if a track were to do so, #511 and #512 told us that such a test, being a bonus, would not be included in the canonical data.

Then there is the matter of the test that is in the https://github.com/exercism/x-common/blob/master/exercises/wordy/canonical-data.json. Since the sentence "What is 52 cubed?" does not match the pattern "What is B raised to the Eth power?" nor any other known operation, it is expected to error, no matter whether a track provides a test for powers.

**Comment by petertseng** [comment]
Since they are two different things, it seems OK to close.

If I were to make a possible suggestion, it is that "What is 52 cubed?" could be changed to a different question, such as "What is the square root of 9?" or something. Less confusion with powers, unless someone is considering the fractional powers.
