### ISSUE TITLE
Update your track information in TRACK_MAINTAINERS.md

### ISSUE THREAD

**Issue by Insti** [exercism/x-common#780]
@exercism/track-maintainers 

https://github.com/exercism/discussions/issues/97 investigated the status of all Exercism language tracks. [`TRACK_MAINTAINERS.md`](https://github.com/exercism/x-common/blob/master/TRACK_MAINTAINERS.md) is intended to continue and maintain that process in a community driven manner.

Please check the entry for your track and submit a PR to ensure that it is in the right section, the current maintainers are listed and that your repository is linked.

See "Ruby" under the "Maintained" section for an example of what information I think there should be for each track.

Feel free to get creative until we can settle on a standard format.

Any of the current text can be considered temporary and any help with the TODO's or rewriting/clarification would be appreciated.

Note to x-common maintainers: please merge TRACK_MAINTAINERS PRs if you see them and they're not obviously broken.

**Comment by Insti** [comment]
Remember to put two spaces at the end of lines so that the markdown renderer will line-break them.

**Comment by petertseng** [comment]
I was thinking of making them sub-bullets... don't know

**Comment by kytrinyx** [comment]
I'd rather have active maintainers for a track listed as part of the config.json file in the track itself. Keeping the information close to home is more likely to keep it relevant, and we can use trackler to display the information in various ways in various places.

**Comment by kytrinyx** [comment]
@Insti I'm going to go ahead and close this in favor of the https://github.com/exercism/discussions/issues/139

I'd like to have the discussion so that we can come to an agreement about how we want to solve it, before jumping to a solution.

**Comment by Insti** [comment]
Are you not interested in having up-to-date information available until you can come up with the perfect solution?

**Comment by Insti** [comment]
Do you want to delete the TRACK_MAINTAINERS file?

**Comment by kytrinyx** [comment]
> Are you not interested in having up-to-date information available until you can come up with the perfect solution?

@Insti You're making a lot of unfair and unfounded assumptions here.

You're suggesting that because I wish to have a discussion first, that I'm not interested in having up-to-date information.

You're assuming that the implementation that you suggested will give us up-to-date information, which based on experience with other cross-track initiatives I would claim is not the case. Getting all the tracks to update something has traditionally been a long-term prospect.

You're implying that it will be quicker to implement this approach—undiscussed—than to spend a few days discussing potential approaches and trade-offs, and come up with something that perhaps serves our needs better.

You're suggesting that because I wish to discuss trade-offs I am waiting for the perfect solution.


> Do you want to delete the TRACK_MAINTAINERS file?

Yes, please delete the file. If you think the TRACK_MAINTAINERS file is the right solution, then please explain your thinking and the trade-offs you're considering over in exercism/discussions#139

I'm not saying you're wrong. I'm saying that I want to discuss the trade-offs before starting an initiative that is going to affect 65 repositories and dozens and dozens of maintainers.

**Comment by Insti** [comment]
Deleted. https://github.com/exercism/x-common/commit/640e8cff8f73875736d2accf378741c0688fe93c

Second thought: Apologies if this should have been a pull request, I just hit the trashcan button in the github interface and it didn't go through the normal process.

**Comment by kytrinyx** [comment]
Ok, thank you.
